### ISSUE TITLE
ASDF in wordpress.org plugin repo

### ISSUE THREAD

**Issue by enejb** [ubc/profile-cct#14]
Hi Loong

If you search ASDF in wordpress.org the only 
https://wordpress.org/plugins/search.php?q=asdf

You get back the Profile plugin. Plugin deploy process. 

Hope you can fix it.

Best Enej

**Comment by loongchan** [comment]
Hey Enej!  
I hope you're doing well!  Thanks for bringing this up!  didn't even notice that mistake!  I just updated the svn repository in wordpress.org and that extra text is now removed.  I hope that's satisfactory?  this github repository doesn't have any reference to the asdf.   

Best,
Loong

**Comment by enejb** [comment]
Hey Loong

Life is good, Thanks for fixing it so fast! 

Best Enej
